### ISSUE TITLE
Publish a new version to the Moodle plugin repo

### ISSUE THREAD

**Issue by abias** [sharpchi/moodle-filter_syntaxhighlighter#14]
Hi Mark,

we are currently in the process of upgrading our Moodle to 3.9 and I am wondering if you could publish a new version of your plugin to https://moodle.org/plugins/pluginversions.php?plugin=filter_syntaxhighlighter which includes the fixes which have been integrated in the last 2 years. That would help us with our deployment and would strengthen your plugin on moodle.org/plugins as well.

Thank you in advance!

Cheers,
Alex

**Comment by abias** [comment]
Hey @sharpchi ,

may I ping you again about this small issue?

Thanks,
Alex

**Comment by lucaboesch** [comment]
@abias I think you can close this issue.
Mark has updated this plugin and added tests, too.
Best,
Luca

**Comment by sharpchi** [comment]
Just updated. Enjoy.
