### ISSUE TITLE
Tag stable releases

### ISSUE THREAD

**Issue by taraghi** [sharpchi/moodle-filter_syntaxhighlighter#17]
Hi,

Our build process fetches the stable code via Github API under the assumption that there is a tag for each plugin release.
Could you please tag the current version and the future releases on Github? It has actually no cost for you and it would support our build process.

Thanks in advance!
Beni

**Comment by sharpchi** [comment]
I've just a new release and tagged it.

**Comment by taraghi** [comment]
Thank you very much! :-)
